## Data Cleansing and Transformation in Python

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
df_crashes = pd.read_csv("data/traffic_crashes.csv")
df_crashes.head()

,crash_record_id,rd_no,crash_date_est_i,crash_date,posted_speed_limit,traffic_control_device,device_condition,weather_condition,lighting_condition,first_crash_type,trafficway_type,lane_cnt,alignment,roadway_surface_cond,road_defect,report_type,crash_type,intersection_related_i,private_property_i,hit_and_run_i,damage,date_police_notified,prim_contributory_cause,sec_contributory_cause,street_no,street_direction,street_name,beat_of_occurrence,photos_taken_i,statements_taken_i,dooring_i,work_zone_i,work_zone_type,workers_present_i,num_units,most_severe_injury,injuries_total,injuries_fatal,injuries_incapacitating,injuries_non_incapacitating,injuries_reported_not_evident,injuries_no_indication,injuries_unknown,crash_hour,crash_day_of_week,crash_month,latitude,longitude,location
0,530411c8611eb0ccb9b25f16b2955cd21761fa1928dcaa...,JE494048,NaN,2021-12-31T14:00:00.000,35,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,TURNING,NOT DIVIDED,NaN,STRAIGHT AND LEVEL,DRY,NO DEFECTS,ON SCENE,INJURY AND / OR TOW DUE TO CRASH,NaN,NaN,NaN,"OVER $1,500",2021-12-31T14:00:00.000,UNABLE TO DETERMINE,NOT APPLICABLE,6021,S,ARCHER AVE,811,NaN,NaN,NaN,NaN,NaN,NaN,2,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,0.0,14,6,12,41.794850,-87.767280,POINT (-87.767280356289 41.794849958048)
1,305b06235b250aa0029c07313c84f969f4bc13c1cc3715...,JE494008,NaN,2021-12-31T14:00:00.000,30,TRAFFIC SIGNAL,UNKNOWN,CLEAR,DUSK,TURNING,FOUR WAY,NaN,STRAIGHT AND LEVEL,DRY,NO DEFECTS,ON SCENE,INJURY AND / OR TOW DUE TO CRASH,Y,NaN,Y,"OVER $1,500",2021-12-31T14:15:00.000,FAILING TO YIELD RIGHT-OF-WAY,DISREGARDING YIELD SIGN,2400,W,MADISON ST,1222,NaN,Y,NaN,NaN,NaN,NaN,3,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,0.0,14,6,12,41.881271,-87.686536,POINT (-87.686535940171 41.881270504288)
2,444221c2a9bc82fc4f301062ab22b482d7d661cf88fcdf...,JE494016,Y,2021-12-31T13:56:00.000,10,OTHER,NO CONTROLS,CLEAR,DAYLIGHT,SIDESWIPE SAME DIRECTION,PARKING LOT,NaN,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NOT ON SCENE (DESK REPORT),NO INJURY / DRIVE AWAY,NaN,Y,NaN,"$501 - $1,500",2021-12-31T14:20:00.000,UNABLE TO DETERMINE,UNABLE TO DETERMINE,9400,S,ASHLAND AVE,2221,NaN,NaN,NaN,NaN,NaN,NaN,2,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,0.0,13,6,12,41.722941,-87.662863,POINT (-87.662862871273 41.72294121821)
3,4603435fbb4ef5d45c0d805c3e9aa5558a311a140a737e...,JE494049,NaN,2021-12-31T13:46:00.000,30,NO CONTROLS,NO CONTROLS,RAIN,DAYLIGHT,PEDALCYCLIST,DIVIDED - W/MEDIAN BARRIER,NaN,STRAIGHT AND LEVEL,WET,NO DEFECTS,NOT ON SCENE (DESK REPORT),INJURY AND / OR TOW DUE TO CRASH,NaN,NaN,NaN,$500 OR LESS,2021-12-31T15:13:00.000,UNABLE TO DETERMINE,UNABLE TO DETERMINE,1910,E,71ST ST,332,NaN,NaN,NaN,NaN,NaN,NaN,2,NONINCAPACITATING INJURY,1.0,0.0,0.0,1.0,0.0,2.0,0.0,13,6,12,41.766336,-87.578270,POINT (-87.578269718478 41.766335621716)
4,db62bb4534d0dae57112ea3ff8d50193784aaa732ed58d...,JE494000,NaN,2021-12-31T13:45:00.000,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,SIDESWIPE SAME DIRECTION,NOT DIVIDED,NaN,STRAIGHT AND LEVEL,WET,NO DEFECTS,ON SCENE,NO INJURY / DRIVE AWAY,NaN,NaN,Y,"OVER $1,500",2021-12-31T15:50:00.000,IMPROPER LANE USAGE,DRIVING SKILLS/KNOWLEDGE/EXPERIENCE,7900,S,LANGLEY AVE,624,NaN,NaN,NaN,NaN,NaN,NaN,2,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,0.0,13,6,12,41.751150,-87.607802,POINT (-87.607802036151 41.7511501753)

In [2]:
df_crashes.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 49 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   crash_record_id                1000 non-null   str
 1   rd_no                          1000 non-null   str
 2   crash_date_est_i               69 non-null     str
 3   crash_date                     1000 non-null   str
 4   posted_speed_limit             1000 non-null   int64
 5   traffic_control_device         1000 non-null   str
 6   device_condition               1000 non-null   str
 7   weather_condition              1000 non-null   str
 8   lighting_condition             1000 non-null   str
 9   first_crash_type               1000 non-null   str
 10  trafficway_type                1000 non-null   str
 11  lane_cnt                       1 non-null      float64
 12  alignment                      1000 non-null   str
 13  roadway_surface_cond           1000 non-null   str
 14  road_defect                    1000 non-null   str
 15  report_type                    976 non-null    str
 16  crash_type                     1000 non-null   str
 17  intersection_related_i         271 non-null    str
 18  private_property_i             45 non-null     str
 19  hit_and_run_i                  320 non-null    str
 20  damage                         1000 non-null   str
 21  date_police_notified           1000 non-null   str
 22  prim_contributory_cause        1000 non-null   str
 23  sec_contributory_cause         1000 non-null   str
 24  street_no                      1000 non-null   int64
 25  street_direction               1000 non-null   str
 26  street_name                    1000 non-null   str
 27  beat_of_occurrence             1000 non-null   int64
 28  photos_taken_i                 15 non-null     str
 29  statements_taken_i             22 non-null     str
 30  dooring_i                      0 non-null      float64
 31  work_zone_i                    4 non-null      str
 32  work_zone_type                 3 non-null      str
 33  workers_present_i              1 non-null      str
 34  num_units                      1000 non-null   int64
 35  most_severe_injury             998 non-null    str
 36  injuries_total                 998 non-null    float64
 37  injuries_fatal                 998 non-null    float64
 38  injuries_incapacitating        998 non-null    float64
 39  injuries_non_incapacitating    998 non-null    float64
 40  injuries_reported_not_evident  998 non-null    float64
 41  injuries_no_indication         998 non-null    float64
 42  injuries_unknown               998 non-null    float64
 43  crash_hour                     1000 non-null   int64
 44  crash_day_of_week              1000 non-null   int64
 45  crash_month                    1000 non-null   int64
 46  latitude                       987 non-null    float64
 47  longitude                      987 non-null    float64
 48  location                       987 non-null    str
dtypes: float64(11), int64(7), str(31)
memory usage: 829.2 KB

In [3]:
df_crashes.notnull().sum()

crash_record_id                  1000
rd_no                            1000
crash_date_est_i                   69
crash_date                       1000
posted_speed_limit               1000
traffic_control_device           1000
device_condition                 1000
weather_condition                1000
lighting_condition               1000
first_crash_type                 1000
trafficway_type                  1000
lane_cnt                            1
alignment                        1000
roadway_surface_cond             1000
road_defect                      1000
report_type                       976
crash_type                       1000
intersection_related_i            271
private_property_i                 45
hit_and_run_i                     320
damage                           1000
date_police_notified             1000
prim_contributory_cause          1000
sec_contributory_cause           1000
street_no                        1000
street_direction                 1000
street_name                      1000
beat_of_occurrence               1000
photos_taken_i                     15
statements_taken_i                 22
dooring_i                           0
work_zone_i                         4
work_zone_type                      3
workers_present_i                   1
num_units                        1000
most_severe_injury                998
injuries_total                    998
injuries_fatal                    998
injuries_incapacitating           998
injuries_non_incapacitating       998
injuries_reported_not_evident     998
injuries_no_indication            998
injuries_unknown                  998
crash_hour                       1000
crash_day_of_week                1000
crash_month                      1000
latitude                          987
longitude                         987
location                          987
dtype: int64

In [4]:
df_crashes.isnull().sum()

crash_record_id                     0
rd_no                               0
crash_date_est_i                  931
crash_date                          0
posted_speed_limit                  0
traffic_control_device              0
device_condition                    0
weather_condition                   0
lighting_condition                  0
first_crash_type                    0
trafficway_type                     0
lane_cnt                          999
alignment                           0
roadway_surface_cond                0
road_defect                         0
report_type                        24
crash_type                          0
intersection_related_i            729
private_property_i                955
hit_and_run_i                     680
damage                              0
date_police_notified                0
prim_contributory_cause             0
sec_contributory_cause              0
street_no                           0
street_direction                    0
street_name                         0
beat_of_occurrence                  0
photos_taken_i                    985
statements_taken_i                978
dooring_i                        1000
work_zone_i                       996
work_zone_type                    997
workers_present_i                 999
num_units                           0
most_severe_injury                  2
injuries_total                      2
injuries_fatal                      2
injuries_incapacitating             2
injuries_non_incapacitating         2
injuries_reported_not_evident       2
injuries_no_indication              2
injuries_unknown                    2
crash_hour                          0
crash_day_of_week                   0
crash_month                         0
latitude                           13
longitude                          13
location                           13
dtype: int64

In [5]:
df_crashes.dropna(axis='columns', how='all', inplace=True)

In [6]:
df_crashes.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 48 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   crash_record_id                1000 non-null   str
 1   rd_no                          1000 non-null   str
 2   crash_date_est_i               69 non-null     str
 3   crash_date                     1000 non-null   str
 4   posted_speed_limit             1000 non-null   int64
 5   traffic_control_device         1000 non-null   str
 6   device_condition               1000 non-null   str
 7   weather_condition              1000 non-null   str
 8   lighting_condition             1000 non-null   str
 9   first_crash_type               1000 non-null   str
 10  trafficway_type                1000 non-null   str
 11  lane_cnt                       1 non-null      float64
 12  alignment                      1000 non-null   str
 13  roadway_surface_cond           1000 non-null   str
 14  road_defect                    1000 non-null   str
 15  report_type                    976 non-null    str
 16  crash_type                     1000 non-null   str
 17  intersection_related_i         271 non-null    str
 18  private_property_i             45 non-null     str
 19  hit_and_run_i                  320 non-null    str
 20  damage                         1000 non-null   str
 21  date_police_notified           1000 non-null   str
 22  prim_contributory_cause        1000 non-null   str
 23  sec_contributory_cause         1000 non-null   str
 24  street_no                      1000 non-null   int64
 25  street_direction               1000 non-null   str
 26  street_name                    1000 non-null   str
 27  beat_of_occurrence             1000 non-null   int64
 28  photos_taken_i                 15 non-null     str
 29  statements_taken_i             22 non-null     str
 30  work_zone_i                    4 non-null      str
 31  work_zone_type                 3 non-null      str
 32  workers_present_i              1 non-null      str
 33  num_units                      1000 non-null   int64
 34  most_severe_injury             998 non-null    str
 35  injuries_total                 998 non-null    float64
 36  injuries_fatal                 998 non-null    float64
 37  injuries_incapacitating        998 non-null    float64
 38  injuries_non_incapacitating    998 non-null    float64
 39  injuries_reported_not_evident  998 non-null    float64
 40  injuries_no_indication         998 non-null    float64
 41  injuries_unknown               998 non-null    float64
 42  crash_hour                     1000 non-null   int64
 43  crash_day_of_week              1000 non-null   int64
 44  crash_month                    1000 non-null   int64
 45  latitude                       987 non-null    float64
 46  longitude                      987 non-null    float64
 47  location                       987 non-null    str
dtypes: float64(10), int64(7), str(31)
memory usage: 821.4 KB

In [7]:
# Dropping rows with too many missing values
df_crashes = df_crashes.dropna(axis='index', thresh=2,
inplace=False)

In [8]:
# Working with missing data

# This column has only two values.
df_crashes['report_type'].unique
# ['ON SCENE', 'NOT ON SCENE (DESK REPORT)', nan]
# Length: 3, dtype: str
# Let's fill the missing value with 'ON SCENE' as below
df_crashes = df_crashes.fillna(value={'report_type': 'ON SCENE'})

In [9]:
# Merging datasets and data aggregation
df_vehicles= pd.read_csv("data/traffic_crash_vehicle.csv")
df_vehicles.head()

,crash_unit_id,crash_record_id,rd_no,crash_date,unit_no,unit_type,num_passengers,vehicle_id,cmrc_veh_i,make,model,lic_plate_state,vehicle_year,vehicle_defect,vehicle_type,vehicle_use,travel_direction,maneuver,towed_i,fire_i,occupant_cnt,exceed_speed_limit_i,towed_by,towed_to,area_00_i,area_01_i,area_02_i,area_03_i,area_04_i,area_05_i,area_06_i,area_07_i,area_08_i,area_09_i,area_10_i,area_11_i,area_12_i,area_99_i,first_contact_point,cmv_id,usdot_no,ccmc_no,ilcc_no,commercial_src,gvwr,carrier_name,carrier_state,carrier_city,hazmat_placards_i,hazmat_name,un_no,hazmat_present_i,hazmat_report_i,hazmat_report_no,mcs_report_i,mcs_report_no,hazmat_vio_cause_crash_i,mcs_vio_cause_crash_i,idot_permit_no,wide_load_i,trailer1_width,trailer2_width,trailer1_length,trailer2_length,total_vehicle_length,axle_cnt,vehicle_config,cargo_body_type,load_type,hazmat_out_of_service_i,mcs_out_of_service_i,hazmat_class
0,1255349,305b06235b250aa0029c07313c84f969f4bc13c1cc3715...,JE494008,2021-12-31T14:00:00.000,1,DRIVER,NaN,1191605.0,NaN,DODGE,CHARGER,IL,NaN,UNKNOWN,UNKNOWN/NA,UNKNOWN/NA,W,TURNING LEFT,Y,NaN,1.0,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,Y,NaN,OTHER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1255350,305b06235b250aa0029c07313c84f969f4bc13c1cc3715...,JE494008,2021-12-31T14:00:00.000,2,DRIVER,NaN,1191608.0,NaN,KIA,SEDONA,IL,2021.0,UNKNOWN,UNKNOWN/NA,UNKNOWN/NA,N,STRAIGHT AHEAD,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,UNKNOWN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1255351,305b06235b250aa0029c07313c84f969f4bc13c1cc3715...,JE494008,2021-12-31T14:00:00.000,3,PARKED,NaN,1191614.0,NaN,CHRYSLER,PACIFICA,IL,2006.0,NONE,VAN/MINI-VAN,PERSONAL,E,PARKED,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,OTHER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1255367,530411c8611eb0ccb9b25f16b2955cd21761fa1928dcaa...,JE494048,2021-12-31T14:00:00.000,1,DRIVER,NaN,1191620.0,NaN,TOYOTA,TUNDRA,IL,2008.0,NONE,PICKUP,PERSONAL,N,U-TURN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,Y,Y,N,NaN,NaN,ROOF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1255368,530411c8611eb0ccb9b25f16b2955cd21761fa1928dcaa...,JE494048,2021-12-31T14:00:00.000,2,DRIVER,NaN,1191622.0,NaN,GENERAL MOTORS CORPORATION (GMC),ENVOY,IL,2003.0,NONE,SPORT UTILITY VEHICLE (SUV),PERSONAL,E,STRAIGHT AHEAD,Y,NaN,1.0,NaN,PRIVATE,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,Y,NaN,OTHER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df = df_crashes.merge(df_vehicles, how = 'left', on='crash_record_id',suffixes=('_left', '_right'))

In [11]:
df.head()

,crash_record_id,rd_no_left,crash_date_est_i,crash_date_left,posted_speed_limit,traffic_control_device,device_condition,weather_condition,lighting_condition,first_crash_type,trafficway_type,lane_cnt,alignment,roadway_surface_cond,road_defect,report_type,crash_type,intersection_related_i,private_property_i,hit_and_run_i,damage,date_police_notified,prim_contributory_cause,sec_contributory_cause,street_no,street_direction,street_name,beat_of_occurrence,photos_taken_i,statements_taken_i,work_zone_i,work_zone_type,workers_present_i,num_units,most_severe_injury,injuries_total,injuries_fatal,injuries_incapacitating,injuries_non_incapacitating,injuries_reported_not_evident,injuries_no_indication,injuries_unknown,crash_hour,crash_day_of_week,crash_month,latitude,longitude,location,crash_unit_id,rd_no_right,crash_date_right,unit_no,unit_type,num_passengers,vehicle_id,cmrc_veh_i,make,model,lic_plate_state,vehicle_year,vehicle_defect,vehicle_type,vehicle_use,travel_direction,maneuver,towed_i,fire_i,occupant_cnt,exceed_speed_limit_i,towed_by,towed_to,area_00_i,area_01_i,area_02_i,area_03_i,area_04_i,area_05_i,area_06_i,area_07_i,area_08_i,area_09_i,area_10_i,area_11_i,area_12_i,area_99_i,first_contact_point,cmv_id,usdot_no,ccmc_no,ilcc_no,commercial_src,gvwr,carrier_name,carrier_state,carrier_city,hazmat_placards_i,hazmat_name,un_no,hazmat_present_i,hazmat_report_i,hazmat_report_no,mcs_report_i,mcs_report_no,hazmat_vio_cause_crash_i,mcs_vio_cause_crash_i,idot_permit_no,wide_load_i,trailer1_width,trailer2_width,trailer1_length,trailer2_length,total_vehicle_length,axle_cnt,vehicle_config,cargo_body_type,load_type,hazmat_out_of_service_i,mcs_out_of_service_i,hazmat_class
0,530411c8611eb0ccb9b25f16b2955cd21761fa1928dcaa...,JE494048,NaN,2021-12-31T14:00:00.000,35,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,TURNING,NOT DIVIDED,NaN,STRAIGHT AND LEVEL,DRY,NO DEFECTS,ON SCENE,INJURY AND / OR TOW DUE TO CRASH,NaN,NaN,NaN,"OVER $1,500",2021-12-31T14:00:00.000,UNABLE TO DETERMINE,NOT APPLICABLE,6021,S,ARCHER AVE,811,NaN,NaN,NaN,NaN,NaN,2,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,0.0,14,6,12,41.794850,-87.767280,POINT (-87.767280356289 41.794849958048),1255367.0,JE494048,2021-12-31T14:00:00.000,1.0,DRIVER,NaN,1191620.0,NaN,TOYOTA,TUNDRA,IL,2008.0,NONE,PICKUP,PERSONAL,N,U-TURN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,Y,Y,N,NaN,NaN,ROOF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,530411c8611eb0ccb9b25f16b2955cd21761fa1928dcaa...,JE494048,NaN,2021-12-31T14:00:00.000,35,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,TURNING,NOT DIVIDED,NaN,STRAIGHT AND LEVEL,DRY,NO DEFECTS,ON SCENE,INJURY AND / OR TOW DUE TO CRASH,NaN,NaN,NaN,"OVER $1,500",2021-12-31T14:00:00.000,UNABLE TO DETERMINE,NOT APPLICABLE,6021,S,ARCHER AVE,811,NaN,NaN,NaN,NaN,NaN,2,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,0.0,14,6,12,41.794850,-87.767280,POINT (-87.767280356289 41.794849958048),1255368.0,JE494048,2021-12-31T14:00:00.000,2.0,DRIVER,NaN,1191622.0,NaN,GENERAL MOTORS CORPORATION (GMC),ENVOY,IL,2003.0,NONE,SPORT UTILITY VEHICLE (SUV),PERSONAL,E,STRAIGHT AHEAD,Y,NaN,1.0,NaN,PRIVATE,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,Y,NaN,OTHER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,305b06235b250aa0029c07313c84f969f4bc13c1cc3715...,JE494008,NaN,2021-12-31T14:00:00.000,30,TRAFFIC SIGNAL,UNKNOWN,CLEAR,DUSK,TURNING,FOUR WAY,NaN,STRAIGHT AND LEVEL,DRY,NO DEFECTS,ON SCENE,INJURY AND / OR TOW DUE TO CRASH,Y,NaN,Y,"OVER $1,500",2021-12-31T14:15:00.000,FAILING TO YIELD RIGHT-OF-WAY,DISREGARDING YIELD SIGN,2400,W,MADISON ST,1222,NaN,Y,NaN,NaN,NaN,3,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,0.0,14,6,12,41.881271,-87.686536,POINT (-87.686535940171 41.881270504288),1255349.0,JE494008,2021-12-31T14:00:00.000,1.0,DRIVER,NaN,1191605.0,NaN,DODGE,CHARGER,IL,NaN,UNKNOWN,UNKNOWN/NA,UNKNOWN/NA,W,TURNING LEFT,Y,NaN,1.0,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,Y,NaN,OTHER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,305b06235b250aa0029c07313c84f969f4bc13c1cc3715...,JE494008,NaN,2021-12-31T14:00:00.000,30,TRAFFIC SIGNAL,UNKNOWN,CLEAR,DUSK,TURNING,FOUR WAY,NaN,STRAIGHT AND LEVEL,DRY,NO DEFECTS,ON SCENE,INJURY AND / OR TOW DUE TO CRASH,Y,NaN,Y,"OVER $1,500",2021-12-31T14:15:00.000,FAILING TO YIELD RIGHT-OF-WAY,DISREGARDING YIELD SIGN,2400,W,MADISON ST,1222,NaN,Y,NaN,NaN,NaN,3,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,0.0,14,6,12,41.881271,-87.686536,POINT (-87.686535940171 41.881270504288),1255350.0,JE494008,2021-12-31T14:00:00.000,2.0,DRIVER,NaN,1191608.0,NaN,KIA,SEDONA,IL,2021.0,UNKNOWN,UNKNOWN/NA,UNKNOWN/NA,N,STRAIGHT AHEAD,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,UNKNOWN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,305b06235b250aa0029c07313c84f969f4bc13c1cc3715...,JE494008,NaN,2021-12-31T14:00:00.000,30,TRAFFIC SIGNAL,UNKNOWN,CLEAR,DUSK,TURNING,FOUR WAY,NaN,STRAIGHT AND LEVEL,DRY,NO DEFECTS,ON SCENE,INJURY AND / OR TOW DUE TO CRASH,Y,NaN,Y,"OVER $1,500",2021-12-31T14:15:00.000,FAILING TO YIELD RIGHT-OF-WAY,DISREGARDING YIELD SIGN,2400,W,MADISON ST,1222,NaN,Y,NaN,NaN,NaN,3,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,0.0,14,6,12,41.881271,-87.686536,POINT (-87.686535940171 41.881270504288),1255351.0,JE494008,2021-12-31T14:00:00.000,3.0,PARKED,NaN,1191614.0,NaN,CHRYSLER,PACIFICA,IL,2006.0,NONE,VAN/MINI-VAN,PERSONAL,E,PARKED,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,OTHER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1510 entries, 0 to 1509
Columns: 119 entries, crash_record_id to hazmat_class
dtypes: float64(35), int64(7), str(77)
memory usage: 2.1 MB

In [13]:
df_agg = df.groupby('vehicle_type').agg({'crash_record_id':'count'}).reset_index()

In [14]:
df_agg

                      vehicle_type  crash_record_id
0                BUS OVER 15 PASS.                5
1       MOPED OR MOTORIZED BICYCLE                1
2                            OTHER               20
3       OTHER VEHICLE WITH TRAILER                1
4                        PASSENGER              633
5                           PICKUP               33
6   SINGLE UNIT TRUCK WITH TRAILER                2
7      SPORT UTILITY VEHICLE (SUV)              138
8          TRACTOR W/ SEMI-TRAILER                5
9         TRACTOR W/O SEMI-TRAILER                2
10             TRUCK - SINGLE UNIT               14
11                      UNKNOWN/NA               89
12                    VAN/MINI-VAN               38

In [15]:
number_of_passenger_cars_involved = df_agg[df_agg['vehicle_type'] ==
'PASSENGER']['crash_record_id'].array[0]

In [16]:
number_of_passenger_cars_involved

np.int64(633)

In [17]:
vehicle_mapping = {'vehicle_type' : 'vehicletypes'}
df_agg = df_agg.rename(columns=vehicle_mapping)

In [18]:
df_agg

                      vehicletypes  crash_record_id
0                BUS OVER 15 PASS.                5
1       MOPED OR MOTORIZED BICYCLE                1
2                            OTHER               20
3       OTHER VEHICLE WITH TRAILER                1
4                        PASSENGER              633
5                           PICKUP               33
6   SINGLE UNIT TRUCK WITH TRAILER                2
7      SPORT UTILITY VEHICLE (SUV)              138
8          TRACTOR W/ SEMI-TRAILER                5
9         TRACTOR W/O SEMI-TRAILER                2
10             TRUCK - SINGLE UNIT               14
11                      UNKNOWN/NA               89
12                    VAN/MINI-VAN               38